- name: Create Network Security Group that allow SSH
  hosts: localhost
  connection: local
  tasks:
  - name: Create Network Security Group
    azure_rm_securitygroup: 
      resource_group: ansibleResourceGroup
      name: sshNetworkSecurityGroup
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
