- hosts: ansibleTestServer
  user: vkaruri
  sudo: true
  tasks:
  - name: symlink imaging library files
    action: file src=/usr/lib/x86_64-linux-gnu/libfreetype.so dest=/usr/lib/libfreetype.so state=link

  - name: symlink imaging library files
    action: file src=/usr/lib/x86_64-linux-gnu/libz.so dest=/usr/lib/libz.so state=link

  - name: symlink imaging library files
    action: file src=/usr/lib/x86_64-linux-gnu/libjpeg.so.62 dest=/usr/lib/x86_64-linux-gnu/libjpeg.so state=link

  - name: symlink imaging library files
    action: file src=/usr/lib/x86_64-linux-gnu/libjpeg.so dest=/usr/lib/libjpeg.so state=link
