- hosts: ansibleTestServer
  become: true
  become_user: root
  tasks:
  - name: create supervisord config folder
    action: file dest=/etc/supervisor state=directory owner=root

  - name: create supervisord config
    action: template src=templates/supervisord.conf dest=/etc/supervisor/supervisord.conf

  - name: create supervisord init script
    action: template src=templates/supervisord.sh dest=/etc/init.d/supervisord mode=0755

  - name: stop supervisord service
    action: service name=supervisor state=stopped
 
  - name: start supervisord service and have it run during system startup
    action: service name=supervisor state=started enabled=yes


