- hosts: ansibleTestServer
  become: true
  tasks:
    - name: add nginx ppa
      action: apt_repository repo=ppa:nginx/stable state=present
       
    - name: install common packages needed for python application development
      action: apt pkg={{item}} state=installed
      with_items:
        - libpq-dev
        - libmysqlclient-dev
        - libxml2-dev
        - libjpeg62
        - libjpeg62-dev
        - libfreetype6
        - libfreetype6-dev
        - zlib1g-dev
        - mysql-client
        - python-dev
        - python-setuptools
        - python-imaging
        - python-mysqldb
        - python-psycopg2
        - git-core
        - nginx
        - gcc
        - supervisor

    - name: install pip
      action: easy_install name=pip

    - name: install various libraries with pip
      action: pip name={{item}} state=present
      with_items:
        - virtualenv
        - uwsgi
     
