version: "3"
  
services:

  flaskapp:
    build: ../
    container_name:  flaskapp

  nginx:
    build: .
    container_name: nginx-flask
    links: 
      - flaskapp:flaskapp
    ports:
      - "9000:80"
